### ISSUE TITLE
Question: is there a way to trigger activity from CLI?

### ISSUE THREAD

**Issue by dangh** [curzel-it/bit-therapy#45]
Hello,

I'm not sure this is the right channel to ask question. If it's not please pardon me.

I want to trigger the activity from CLI, maybe just random action like jumping, so I can let the kitten celebrate with me when my code build successfully. Is that possible?

Thank you. I love the pets.

**Comment by curzel-it** [comment]
Hello!
It’s currently not possible, but I will look into it later today, sounds
like something cool to add!

Il giorno lun 4 set 2023 alle 20:21 Dang ***@***.***> ha
scritto:

**Comment by curzel-it** [comment]
@dangh Here you go!
https://github.com/curzel-it/pet-therapy/#-interoperability

If you have any feedback, please let me know

**Comment by curzel-it** [comment]
@dangh Hello! Just letting you know v2.48 is being released in a couple of days, see ya!
