### ISSUE TITLE
Instruction pages for custom pet is not working

### ISSUE THREAD

**Issue by GenSSK** [curzel-it/bit-therapy#51]
Hello,
I discovered this app a few hours ago and am already hooked.
I wanted to create a custom pet and tried to look at the instructions, but it is a 404 not found.

**Comment by curzel-it** [comment]
Hi @GenSSK !
Thanks for reporting, I've recently changed the app name from "Desktop Pets" to "BitTherapy" to match my [YouTube channel](https://www.youtube.com/@BitTherapy) and forgot to update stuff 😅 

The docs you are looking fore is [here](https://curzel.it/bit-therapy/custompets), enjoy!

**Comment by curzel-it** [comment]
Hi @GenSSK !
Thanks for reporting, I've recently changed the app name from "Desktop Pets" to "BitTherapy" to match my [YouTube channel](https://www.youtube.com/@BitTherapy) and forgot to update stuff 😅 

The docs you are looking fore is [here](https://curzel.it/bit-therapy/custompets), enjoy!

**Comment by curzel-it** [comment]
Hi @GenSSK !
Thanks for reporting, I've recently changed the app name from "Desktop Pets" to "BitTherapy" to match my [YouTube channel](https://www.youtube.com/@BitTherapy) and forgot to update stuff 😅 

The docs you are looking fore is [here](https://curzel.it/bit-therapy/custompets), enjoy!
